In [31]:
import pandas as pd
pf = pd.read_csv(r"C:\Users\acer\Downloads\customer_shopping_behavior.csv")
print(pf.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)       Location Size      Color  Season  Review Rating Subscription Status  Shipping Type Discount Applied Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0            1   55   Male         Blouse  Clothing                     53       Kentucky    L       Gray  Winter            3.1                 Yes        Express              Yes             Yes                  14          Venmo            Fortnightly
1            2   19   Male        Sweater  Clothing                     64          Maine    L     Maroon  Winter            3.1                 Yes        Express              Yes             Yes                   2           Cash            Fortnightly
2            3   50   Male          Jeans  Clothing                     73  Massachusetts    S     Maroon  Spring            3.1                 Yes  Free Shipping              Yes             Yes                  23    Credit Card                 Weekly
3            4   21   Male        Sandals  Footwear                     90   Rhode Island    M     Maroon  Spring            3.5                 Yes   Next Day Air              Yes             Yes                  49         PayPal                 Weekly
4            5   45   Male         Blouse  Clothing                     49         Oregon    M  Turquoise  Spring            2.7                 Yes  Free Shipping              Yes             Yes                  31         PayPal               Annually

In [32]:
pf.info

<bound method DataFrame.info of       Customer ID  Age  Gender Item Purchased     Category  Purchase Amount (USD)       Location Size      Color  Season  Review Rating Subscription Status   Shipping Type Discount Applied Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0               1   55    Male         Blouse     Clothing                     53       Kentucky    L       Gray  Winter            3.1                 Yes         Express              Yes             Yes                  14          Venmo            Fortnightly
1               2   19    Male        Sweater     Clothing                     64          Maine    L     Maroon  Winter            3.1                 Yes         Express              Yes             Yes                   2           Cash            Fortnightly
2               3   50    Male          Jeans     Clothing                     73  Massachusetts    S     Maroon  Spring            3.1                 Yes   Free Shipping              Yes             Yes                  23    Credit Card                 Weekly
3               4   21    Male        Sandals     Footwear                     90   Rhode Island    M     Maroon  Spring            3.5                 Yes    Next Day Air              Yes             Yes                  49         PayPal                 Weekly
4               5   45    Male         Blouse     Clothing                     49         Oregon    M  Turquoise  Spring            2.7                 Yes   Free Shipping              Yes             Yes                  31         PayPal               Annually
...           ...  ...     ...            ...          ...                    ...            ...  ...        ...     ...            ...                 ...             ...              ...             ...                 ...            ...                    ...
3895         3896   40  Female         Hoodie     Clothing                     28       Virginia    L  Turquoise  Summer            4.2                  No  2-Day Shipping               No              No                  32          Venmo                 Weekly
3896         3897   52  Female       Backpack  Accessories                     49           Iowa    L      White  Spring            4.5                  No    Store Pickup               No              No                  41  Bank Transfer              Bi-Weekly
3897         3898   46  Female           Belt  Accessories                     33     New Jersey    L      Green  Spring            2.9                  No        Standard               No              No                  24          Venmo              Quarterly
3898         3899   44  Female          Shoes     Footwear                     77      Minnesota    S      Brown  Summer            3.8                  No         Express               No              No                  24          Venmo                 Weekly
3899         3900   52  Female        Handbag  Accessories                     81     California    M      Beige  Spring            3.1                  No    Store Pickup               No              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [33]:
pf.describe

<bound method NDFrame.describe of       Customer ID  Age  Gender Item Purchased     Category  Purchase Amount (USD)       Location Size      Color  Season  Review Rating Subscription Status   Shipping Type Discount Applied Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0               1   55    Male         Blouse     Clothing                     53       Kentucky    L       Gray  Winter            3.1                 Yes         Express              Yes             Yes                  14          Venmo            Fortnightly
1               2   19    Male        Sweater     Clothing                     64          Maine    L     Maroon  Winter            3.1                 Yes         Express              Yes             Yes                   2           Cash            Fortnightly
2               3   50    Male          Jeans     Clothing                     73  Massachusetts    S     Maroon  Spring            3.1                 Yes   Free Shipping              Yes             Yes                  23    Credit Card                 Weekly
3               4   21    Male        Sandals     Footwear                     90   Rhode Island    M     Maroon  Spring            3.5                 Yes    Next Day Air              Yes             Yes                  49         PayPal                 Weekly
4               5   45    Male         Blouse     Clothing                     49         Oregon    M  Turquoise  Spring            2.7                 Yes   Free Shipping              Yes             Yes                  31         PayPal               Annually
...           ...  ...     ...            ...          ...                    ...            ...  ...        ...     ...            ...                 ...             ...              ...             ...                 ...            ...                    ...
3895         3896   40  Female         Hoodie     Clothing                     28       Virginia    L  Turquoise  Summer            4.2                  No  2-Day Shipping               No              No                  32          Venmo                 Weekly
3896         3897   52  Female       Backpack  Accessories                     49           Iowa    L      White  Spring            4.5                  No    Store Pickup               No              No                  41  Bank Transfer              Bi-Weekly
3897         3898   46  Female           Belt  Accessories                     33     New Jersey    L      Green  Spring            2.9                  No        Standard               No              No                  24          Venmo              Quarterly
3898         3899   44  Female          Shoes     Footwear                     77      Minnesota    S      Brown  Summer            3.8                  No         Express               No              No                  24          Venmo                 Weekly
3899         3900   52  Female        Handbag  Accessories                     81     California    M      Beige  Spring            3.1                  No    Store Pickup               No              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [34]:
pf.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [35]:
pf["Review Rating"] = pf.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [36]:
pf.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [77]:
pf.columns = pf.columns.str.lower()
pf.columns = pf.columns.str.replace(' ','_')
pf = pf.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [78]:
pf.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases'], dtype='object')

In [79]:
# create a colums age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
pf['age_group'] = pd.qcut(pf['age'], q=4, labels = labels)

In [80]:
pf[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [81]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Quarterly': 30,
    "Bi-Weekly": 14,
    "Annually": 365,
    "Every 3 Months": 90
}

pf['purchase_frequency_days'] = pf["frequency_of_purchases"].map(frequency_mapping)

In [82]:
pf[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     30.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     30.0              Quarterly

In [83]:
pf[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [84]:
(pf['discount_applied'] == pf['promo_code_used']).all()

np.True_

In [86]:
pf = pf.drop('promo_code_used',axis = 1)

In [87]:
pf.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'age_group', 'purchase_frequency_days'], dtype='object')

In [88]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)
Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ----------------------- ---------------- 1.6/2.7 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 10.0 MB/s  0:00:00
Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 21.3 MB/s  0:00:00
Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [psycopg2-binary]
   ---------------------------------------- 0/3 [psycopg2-binary]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.2.4 psycopg2-binary-2.9.11 sqlalchemy-2.0.44
Note: you may need to restart the kernel to use updated packages.

In [96]:
from sqlalchemy import create_engine

username = 'postgres'
password = 'Aniket%40270204' 
host = 'localhost'
port = '5432'
database = 'Customer_Behavior'

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

table_name = 'customer'
pf.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'Customer_Behavior'.